## Initialization

In [1]:
from active_learning.al_HER_sulfide import AL
from utils.utils import get_tasks

# exp selection
# exp_name = 'acidic_mor_PtRuSc'
exp_name = 'Ali_HER_sulfide'
# exp_name = 'DFFC_PdPtCu'
#exp_name = 'DFFC_8D_4'

## Save and load

In [2]:
# load al instance from database
al = AL(exp_name)

In [11]:
# save the current al instance to the database
al.save_exp_to_db()

## AL main workflow

### recipe generation

In [3]:
%%time
# generate next trial using Bayesian Optimization, specify beta if needed, e.g. beta=100 for exploration, beta=0.2 for default
al.generate_botorch_trial(n=30, aquisition = 'qUCB', optimizer_kwargs = {'options':{'maxiter':20000000}, 'sequential':True})

BO trial successfully added as trial 1
CPU times: total: 14min 52s
Wall time: 6min 18s

In [1]:
# generate next trial using SOBOL method (random select)
al.generate_sobol_trial(n=20)

NameError: name 'al' is not defined

In [6]:
# update the recipe table on the database, if trial index is not specified, the recipe of the latest trial will be uploaded
al.update_recipe_table(trial_index=None, add_pred=False)

### sample preparation

In [7]:
# benchmark specification
benchmark = None
# benchmark={5: '1_0'}

In [ ]:
# command opentrons to prepare the sample for the latest trial, following the ot2_run_configs of the exp
al.make_sample(trial_index=None, benchmark=benchmark, operator_name='chu')

In [8]:
# update the sample table on the database, if trial index is not specified, the sample of the latest trial will be uploaded. Note that sample table calculation is based on local ot2_run_configs.py under project folder, not the one on ot2 server.
al.update_sample_table(trial_index=None, benchmark=benchmark)

### sample testing complete

In [9]:
# run this cell after sample testing and data analysis is completed, then go back to the BO step
al.mark_trial_complete(trial_index=None)

BatchTrial(experiment_name='Ali_HER_sulfide', index=0, status=TrialStatus.RUNNING)

## AL monitor

In [ ]:
# update the exp with the latest result
al.update_exp_result()

In [4]:
# exp monitor for windows
al.exp_monitor()

,arm_name,trial_index,arm_index,Pt,Ni,Mo,Co,Cu,Fe,pred_mean,pred_std,potential,trial_status,generation_method
0,0_0,0,0,0.750,0.250,0.000,0.000,0.000,0.000,-2.039,0.04107,-2.07,COMPLETED,Manual
1,0_1,0,1,0.750,0.000,0.250,0.000,0.000,0.000,-2.044,0.03517,-2.03,COMPLETED,Manual
2,0_2,0,2,0.750,0.000,0.000,0.250,0.000,0.000,-2.033,0.03697,-2.06,COMPLETED,Manual
3,0_3,0,3,0.750,0.000,0.000,0.000,0.250,0.000,-2.051,0.03707,-2.04,COMPLETED,Manual
4,0_4,0,4,0.750,0.125,0.125,0.000,0.000,0.000,-1.983,0.03400,-2.00,COMPLETED,Manual
5,0_5,0,5,0.750,0.125,0.000,0.125,0.000,0.000,-1.957,0.03389,-1.91,COMPLETED,Manual
6,0_6,0,6,0.750,0.000,0.125,0.125,0.000,0.000,-2.036,0.03011,-2.00,COMPLETED,Manual
7,0_7,0,7,0.750,0.125,0.000,0.000,0.125,0.000,-1.967,0.03398,-1.93,COMPLETED,Manual
8,0_8,0,8,0.750,0.000,0.125,0.000,0.125,0.000,-2.060,0.03021,-2.13,COMPLETED,Manual
9,1_0,1,0,0.647,0.131,0.000,0.166,0.056,0.000,-1.958,0.03836,NaN,RUNNING,BoTorch
10,1_1,1,1,0.568,0.129,0.000,0.155,0.014,0.134,-1.969,0.04907,NaN,RUNNING,BoTorch
19,1_10,1,10,0.136,0.172,0.000,0.692,0.000,0.000,-2.020,0.07891,NaN,RUNNING,BoTorch
20,1_11,1,11,0.341,0.122,0.000,0.001,0.000,0.536,-2.024,0.07913,NaN,RUNNING,BoTorch
21,1_12,1,12,0.267,0.136,0.000,0.283,0.215,0.099,-1.985,0.06387,NaN,RUNNING,BoTorch
22,1_13,1,13,0.209,0.138,0.000,0.314,0.000,0.339,-2.006,0.07435,NaN,RUNNING,BoTorch
23,1_14,1,14,0.465,0.139,0.000,0.271,0.109,0.016,-1.970,0.05417,NaN,RUNNING,BoTorch
24,1_15,1,15,0.000,0.160,0.078,0.217,0.117,0.428,-2.016,0.07723,NaN,RUNNING,BoTorch
25,1_16,1,16,0.000,0.211,0.000,0.379,0.177,0.233,-2.013,0.07539,NaN,RUNNING,BoTorch
26,1_17,1,17,0.208,0.079,0.083,0.125,0.000,0.505,-2.024,0.07836,NaN,RUNNING,BoTorch
27,1_18,1,18,0.164,0.184,0.000,0.058,0.594,0.000,-2.019,0.07743,NaN,RUNNING,BoTorch
28,1_19,1,19,0.035,0.105,0.200,0.345,0.099,0.216,-2.008,0.07142,NaN,RUNNING,BoTorch
11,1_2,1,2,0.445,0.144,0.000,0.192,0.219,0.000,-1.974,0.05531,NaN,RUNNING,BoTorch
29,1_20,1,20,0.577,0.148,0.000,0.142,0.112,0.021,-1.962,0.04169,NaN,RUNNING,BoTorch
30,1_21,1,21,0.394,0.145,0.000,0.332,0.001,0.128,-1.984,0.06281,NaN,RUNNING,BoTorch
31,1_22,1,22,0.391,0.124,0.137,0.187,0.100,0.061,-1.979,0.05078,NaN,RUNNING,BoTorch
32,1_23,1,23,0.355,0.134,0.095,0.295,0.000,0.121,-1.984,0.06014,NaN,RUNNING,BoTorch
33,1_24,1,24,0.434,0.147,0.008,0.354,0.038,0.019,-1.981,0.06112,NaN,RUNNING,BoTorch
34,1_25,1,25,0.337,0.141,0.010,0.132,0.201,0.179,-1.984,0.06054,NaN,RUNNING,BoTorch
35,1_26,1,26,0.322,0.146,0.000,0.218,0.268,0.046,-1.983,0.06202,NaN,RUNNING,BoTorch
36,1_27,1,27,0.279,0.139,0.033,0.256,0.034,0.259,-1.994,0.06804,NaN,RUNNING,BoTorch
37,1_28,1,28,0.703,0.118,0.000,0.179,0.000,0.000,-1.960,0.03849,NaN,RUNNING,BoTorch
38,1_29,1,29,0.000,0.201,0.000,0.243,0.395,0.161,-2.012,0.07521,NaN,RUNNING,BoTorch
12,1_3,1,3,0.523,0.143,0.000,0.334,0.000,0.000,-1.977,0.05838,NaN,RUNNING,BoTorch
13,1_4,1,4,0.379,0.141,0.000,0.120,0.210,0.150,-1.981,0.05783,NaN,RUNNING,BoTorch
14,1_5,1,5,0.739,0.124,0.000,0.137,0.000,0.000,-1.958,0.03475,NaN,RUNNING,BoTorch
15,1_6,1,6,0.208,0.138,0.216,0.308,0.013,0.117,-1.997,0.06639,NaN,RUNNING,BoTorch
16,1_7,1,7,0.660,0.121,0.000,0.000,0.000,0.219,-1.989,0.05948,NaN,RUNNING,BoTorch
17,1_8,1,8,0.226,0.156,0.000,0.451,0.167,0.000,-1.998,0.07171,NaN,RUNNING,BoTorch
18,1_9,1,9,0.470,0.155,0.000,0.005,0.370,0.000,-1.996,0.06355,NaN,RUNNING,BoTorch

In [4]:
# exp monitor for mac and linux
from IPython.display import display, HTML
display(HTML(al.exp_monitor().to_html()))

In [ ]:
# check abandon reason
al.exp.trials[0].abandoned_reason

## AL manual edit

In [ ]:
# update the exp with the latest result and force match previous trials with the results in the database
al.update_exp_result(force_update_trial=[0, 1])

In [5]:
# manually add a trial
trial_df = get_tasks(exp_name, task_name='manual_1')
al.add_manual_trial(trial_df)

    Ni   Mo   Co   Cu   Fe   Pt
0  1.0  0.0  0.0  0.0  0.0  3.0
1  0.0  1.0  0.0  0.0  0.0  3.0
2  0.0  0.0  1.0  0.0  0.0  3.0
3  0.0  0.0  0.0  1.0  0.0  3.0
4  0.5  0.5  0.0  0.0  0.0  3.0
5  0.5  0.0  0.5  0.0  0.0  3.0
6  0.0  0.5  0.5  0.0  0.0  3.0
7  0.5  0.0  0.0  0.5  0.0  3.0
8  0.0  0.5  0.0  0.5  0.0  3.0

Please double check task list as above
manual trial successfully added as trial 0

In [ ]:
# abandon an certain arm in a trial
al.abandon_arm(0, '0_18', 'abandoned in manual test')

In [ ]:
# abandon a whole trial
al.abandon_trial(9, 'test trial')

## Plotting

In [ ]:
from ax.modelbridge.cross_validation import cross_validate
from ax.plot.contour import interact_contour
from ax.plot.diagnostic import interact_cross_validation
from ax.plot.scatter import interact_fitted
from ax.plot.slice import interact_slice
from ax.utils.notebook.plotting import render, init_notebook_plotting
init_notebook_plotting()

In [ ]:
model = al.get_bo_model()

In [ ]:
# Contour plots
render(interact_contour(model=model, metric_name='max_power'))

In [ ]:
# Cross-validation plots
cv_results = cross_validate(model)
print('current r_squared is: ', al.calculate_r_squared(cv_results))
render(interact_cross_validation(cv_results))

In [ ]:
# Slice plots
render(interact_slice(model))

In [ ]:
# Tile plots
render(interact_fitted(model, rel=False))

## Danger Zone

In [ ]:
# delete the current active learning process from the database
al.delete_exp_on_db()

In [2]:
# only use this if you want to start a new experiment, note that the previous experiment has to be manually deleted, first, because the script refuses to overwrite the previous experiment by default
al = AL(exp_name, load_from_db=False)

Database Ali_HER_sulfide does not exist yet, creating now...
Table recipe does not exist on server yet, creating now...
Table sample does not exist on server yet, creating now...
Table performance does not exist on server yet, creating now...
full table view created